---
abstract: Redacted
author:
  - 'Brian Phillips <bphillips@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101461, CPAN::Meta::Converter version 2.101461'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DR-SAP
version: 0.16
